/**
 * Returns an array of time values
 * @param 
 * @return String[]
 */
function getTimeArray() {
    return [
            '00:00',
            '00:30',
            '01:30',
            '02:00',
            '02:30',
            '03:00',
            '03:30',
            '04:00',
            '04:30',
            '05:00',
            '05:30',
            '06:00',
            '06:30',
            '07:00',
            '07:30',
            '08:00',
            '08:30',
            '09:00',
            '09:30',
            '10:00',
            '10:30',
            '11:00',
            '11:30',
            '12:00',
            '12:30',
            '13:00',
            '13:30',
            '14:00',
            '14:30',
            '15:00',
            '15:30',
            '16:00',
            '16:30',
            '17:00',
            '17:30',
            '18:00',
            '18:30',
            '19:00',
            '19:30',
            '20:00',
            '20:30',
            '21:00',
            '21:30',
            '22:00',
            '22:30',
            '23:00',
            '23:30'];
}

/**
 * Returns an array of nationalities
 * @param 
 * @return String[]
 */
function getNationalityArray() {
    return [
        'Singapore | Singaporean',
        'Afghanistan | Afghan',
        'Albania | Albanian',
        'Algeria | Algerian',
        'USA | American',
        'Andorra | Andorran',
        'Angola | Angolan',
        'Antigua | Antiguans',
        'Argentina | Argentinean',
        'Armenia | Armenian',
        'Australia | Australian',
        'Austria | Austrian',
        'Azerbaijan | Azerbaijani',
        'Bahamas | Bahamian',
        'Bahrain | Bahraini',
        'Bangladesh | Bangladeshi',
        'Barbados | Barbadian',
        'Barbuda | Barbudans',
        'Bostwana | Batswana',
        'Belarus | Belarusian',
        'Belgium | Belgian',
        'Belize | Belizean',
        'Benin | Beninese',
        'Bhutan | Bhutanese',
        'Bolivia | Bolivian',
        'Bosnia | Bosnian',
        'Brazil | Brazilian',
        'United Kingdom | British',
        'Brunei | Bruneian',
        'Bulgaria | Bulgarian',
        'Burkina Faso | Burkinabe',
        'Burma | Burmese',
        'Burundi | Burundian',
        'Cambodia | Cambodian',
        'Cameron | Cameroonian',
        'Canada | Canadian',
        'Cape Verde | Cape Verdean',
        'Africa | Central African',
        'Chad | Chadian',
        'Chile | Chilean',
        'China | Chinese',
        'Colombia | Colombian',
        'Comoros | Comoran',
        'Congo | Congolese',
        'Costa Rica | Costa Rican',
        'Croatia | Croatian',
        'Cuba | Cuban',
        'Cyprus | Cypriot',
        'Czech Republic | Czech',
        'Denmark | Danish',
        'Djibouti',
        'Dominican',
        'Netherlands | Dutch',
        'East Timor | East Timorese',
        'Ecuador | Ecuadorean',
        'Egypt | Egyptian',
        'United Arab Emirates | Emirian',
        'Equatorial Guinea | Equatorial Guinean',
        'Eritrea | Eritrean',
        'Estonia | Estonian',
        'Ethiopia | Ethiopian',
        'Fiji | Fijian',
        'Philippines | Filipino',
        'Finland | Finnish',
        'France | French',
        'Gabon | Gabonese',
        'Gambia | Gambian',
        'Georgia | Georgian',
        'Germany | German',
        'Ghana | Ghanaian',
        'Greece | Greek',
        'Grenada | Grenadian',
        'Guatemala | Guatemalan',
        'Guinea-Bissauan',
        'Guinea | Guinean',
        'Guyana | Guyanese',
        'Haiti | Haitian',
        'Herzegovina | Herzegovinian',
        'Honduras | Honduran',
        'Hungary | Hungarian',
        'Kiribati | I-Kiribati',
        'Iceland | Icelander',
        'India | Indian',
        'Indonesia | Indonesian',
        'Iran | Iranian',
        'Iraq | Iraqi',
        'Ireland | Irish',
        'Israel | Israeli',
        'Italy | Italian',
        'Ivory Coast | Ivorian',
        'Jamaica | Jamaican',
        'Japan | Japanese',
        'Jordan | Jordanian',
        'Kazakhstan | Kazakhstani',
        'Kenya | Kenyan',
        'Kittian and Nevisian',
        'Kuwait | Kuwaiti',
        'Kyrgyzstan | Kyrgyz',
        'Laos | Laotian',
        'Lativa | Latvian',
        'Lebanon | Lebanese',
        'Liberia | Liberian',
        'Libya | Libyan',
        'Liechtenstein | Liechtensteiner',
        'Lituania | Lithuanian',
        'Luxembourg | Luxembourger',
        'Macedonia | Macedonian',
        'Madagascar | Malagasy',
        'Malawi | Malawian',
        'Malaysia | Malaysian',
        'Maldives | Maldivan',
        'Mali | Malian',
        'Malta | Maltese',
        'Marshallese',
        'Mauritanian',
        'Mauritius | Mauritian',
        'Mexico | Mexican',
        'Micronesia | Micronesian',
        'Moldovan',
        'Monaco | Monacan',
        'Mongolia | Mongolian',
        'Morocco | Moroccan',
        'Mosotho',
        'Motswana',
        'Mozambique | Mozambican',
        'Namibia | Namibian',
        'Nauruan',
        'Nepal | Nepalese',
        'New Zealand | New Zealander',
        'Nicaraguan',
        'Nigeria | Nigerian',
        'Nigerien',
        'North Korean',
        'Northern Irish',
        'Norway | Norwegian',
        'Omani',
        'Pakistan | Pakistani',
        'Palauan',
        'Panamanian',
        'Papua New Guinean',
        'Paraguay | Paraguayan',
        'Peru | Peruvian',
        'Poland | Polish',
        'Portugal | Portuguese',
        'Qatar | Qatari',
        'Romania | Romanian',
        'Russia | Russian',
        'Rwanda | Rwandan',
        'Saint Lucian',
        'Salvadoran',
        'Samoan',
        'San Marinese',
        'Sao Tomean',
        'Saudi Arabia | Saudi',
        'Scotland | Scottish',
        'Senegalese',
        'Serbia | Serbian',
        'Seychellois',
        'Sierra Leone | Sierra Leonean',
        'Slovakia | Slovakian',
        'Slovenia | Slovenian',
        'Solomon Islander',
        'Somali',
        'South African',
        'Korea | South Korean',
        'Spain | Spanish',
        'Sri Lanka | Sri Lankan',
        'Sudan | Sudanese',
        'Surinamer',
        'Swazi',
        'Sweden | Swedish',
        'Switzerland | Swiss',
        'Syria | Syrian',
        'Taiwan | Taiwanese',
        'Tajik',
        'Tanzania | Tanzanian',
        'Thailand | Thai',
        'Togolese',
        'Tongan',
        'Trinidadian/Tobagonian',
        'Tunisia | Tunisian',
        'Turkey | Turkish',
        'Tuvaluan',
        'Uganda | Ugandan',
        'Ukrain | Ukrainian',
        'Uruguay | Uruguayan',
        'Uzbekistan | Uzbekistani',
        'Venezuela | Venezuelan',
        'Vietnam | Vietnamese',
        'Welsh',
        'Yemenite',
        'Zambian',
        'Zimbabwean'];
}

/**
 * Returns String containing the current time
 * @param 
 * @return String
 */
function getCurrentTime() {
    var d = new Date();
    var localTime = d.getTime();
    var localOffset = d.getTimezoneOffset() * 60000;
    var utc = localTime + localOffset;
    var offset = 8;
    var singaporeTime = utc + (3600000 * offset);
    var date = new Date(singaporeTime);
    var timeStr = "";
    if (date.getMinutes() > 30) {
        if (date.getHours() == 23) {
            timeStr = "00:00";
        } else if (date.getHours() < 9) {
            timeStr = "0" + (date.getHours() + 1) + ":00";
        } else {
            timeStr = (date.getHours() + 1) + ":00";
        }
    } else {
        if (date.getHours() < 9) {
            timeStr = "0" + date.getHours() + ":30";
        } else {
            timeStr = (date.getHours()) + ":30";
        }
    }
    return timeStr;
}